name       : josm
version    : 15121
release    : 1
source     :
    - https://getsol.us/sources/josm-15121.tar.xz : 3006f1cf8970f39e82dda5a6d4ac46555173b4edcc378c82383951d0b7dd5c7d
license    : GPL-2.0-or-later
component  : office
summary    : An extensible editor for ​OpenStreetMap
description: |
    JOSM is an extensible editor for ​OpenStreetMap. It supports loading GPX tracks, background imagery and OSM data from local sources as well as from online sources and allows to edit the OSM data (nodes, ways, and relations) and their metadata tags. 
builddeps  :
    - apache-ant
rundeps    :
    - openjdk-8
setup      : |
    to_replace='${version.entry.commit.revision}'
    sed -e "s|$to_replace|$version|g" -i build.xml
build      : |
    ant dist
install    : |
    install -Dm00755 dist/josm-custom.jar $installdir/usr/share/josm/josm.jar
    cp -a linux/tested/usr/share/{applications,icons,man,metainfo,pixmaps} $installdir/usr/share
    install -Dm00755 $pkgfiles/josm -t $installdir/usr/bin
