name       : josm
version    : 15234
release    : 3
source     :
    - https://getsol.us/sources/josm-15234.tar.xz : de7336fbff1f3b173659c7e29688aa45f702bff27be57413121a8437d390ef32
license    : GPL-2.0-or-later
component  : office
summary    : An extensible editor for ​OpenStreetMap
description: |
    JOSM is an extensible editor for ​OpenStreetMap. It supports loading GPX tracks, background imagery and OSM data from local sources as well as from online sources and allows to edit the OSM data (nodes, ways, and relations) and their metadata tags. 
builddeps  :
    - apache-ant
rundeps    :
    - openjdk-8
setup      : |
    sed -e "s|\${version.entry.commit.revision}|$version|g" -i build.xml
build      : |
    ant dist
install    : |
    install -Dm00755 dist/josm-custom.jar $installdir/usr/share/josm/josm.jar
    cp -a linux/tested/usr/share/{applications,icons,man,metainfo,pixmaps} $installdir/usr/share
    install -Dm00755 $pkgfiles/josm -t $installdir/usr/bin
