name       : josm
version    : '18193'
release    : 9
source     :
    - https://github.com/JOSM/josm/archive/refs/tags/18193-tested.tar.gz : 373a0da3fa8d4e9732d079e0a026f36dc3f7bbd6ca3f07ea1f8e2add151e73a5
license    : GPL-2.0-or-later
component  : office
summary    : An extensible editor for OpenStreetMap
description: |
    JOSM is an extensible editor for OpenStreetMap. It supports loading GPX tracks, background imagery and OSM data from local sources as well as from online sources and allows to edit the OSM data (nodes, ways, and relations) and their metadata tags.
networking : yes
builddeps  :
    - apache-ant
rundeps    :
    - openjdk-11
setup      : |
    sed -e "s|\${version.entry.commit.revision}|$version|g" -i build.xml
build      : |
    ant dist -Divy.default.ivy.user.dir=$workdir/.ivy2
install    : |
    install -Dm00755 dist/josm-custom.jar $installdir/usr/share/josm/josm.jar
    install -Dm00755 $pkgfiles/josm -t $installdir/usr/bin

    find native/linux/tested/usr/share -type d -empty -delete
    rm -rf native/linux/tested/usr/share/doc
    cp -a native/linux/tested/usr/share $installdir/usr
