name       : josm
version    : '17428'
release    : 8
source     :
    - https://getsol.us/sources/josm-17428.tar.xz : 7281c7b3a9148056e5f8715ab09ce87ca477a80e8245c9ca242d9e3bf66fe404
license    : GPL-2.0-or-later
component  : office
summary    : An extensible editor for OpenStreetMap
description: |
    JOSM is an extensible editor for OpenStreetMap. It supports loading GPX tracks, background imagery and OSM data from local sources as well as from online sources and allows to edit the OSM data (nodes, ways, and relations) and their metadata tags.
networking : yes
builddeps  :
    - apache-ant
rundeps    :
    - openjdk-11
setup      : |
    sed -e "s|\${version.entry.commit.revision}|$version|g" -i build.xml
build      : |
    ant dist -Divy.default.ivy.user.dir=$workdir/.ivy2
install    : |
    install -Dm00755 dist/josm-custom.jar $installdir/usr/share/josm/josm.jar
    install -Dm00755 $pkgfiles/josm -t $installdir/usr/bin

    find native/linux/tested/usr/share -type d -empty -delete
    rm -rf native/linux/tested/usr/share/doc
    cp -a native/linux/tested/usr/share $installdir/usr
